# Generated by Django 4.0.4 on 2022-05-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_torrent_file_message_magnet_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.TextField(default='NA'),
        ),
    ]
